services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: jupyter lab --notebook-dir=/app --ip=0.0.0.0 --no-browser --allow-root --port=8888 --ServerApp.token='' --ServerApp.password='' --ServerApp.allow_origin='*' --ServerApp.base_url=/
    image: zero-shot:v1.0.0
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "8888:8888"
  serve:
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility]
    command: uvicorn app:app --workers=1 --host '0.0.0.0' --port 8080
    image: zero-shot:v1.0.0
    ports:
      - "8080:8080"
